# -*- coding: utf-8 -*-
"""untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/kebjam/538245b6b5574070dce7d4eb2ac98151/untitled5.ipynb
"""

# Importation des bibliothèques nécessaires"

import streamlit as st
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from langdetect import detect

# Configuration de la page Streamlit
st.set_page_config(
    page_title="Résumé Automatique (FR/EN)",
    layout="wide"
)

st.title("Résumé Automatique (FR/EN)")
st.markdown("Collez un texte en français ou en anglais. Le modèle détectera la langue et générera un résumé dans la même langue.")

@st.cache_resource
def load_models():
    # Chargement des modèles
    model_fr = AutoModelForSeq2SeqLM.from_pretrained("plguillou/t5-base-fr-sum-cnndm")
    tokenizer_fr = AutoTokenizer.from_pretrained("plguillou/t5-base-fr-sum-cnndm")
    model_en = AutoModelForSeq2SeqLM.from_pretrained("facebook/bart-large-cnn")
    tokenizer_en = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
    return model_fr, tokenizer_fr, model_en, tokenizer_en

# Chargement des modèles avec mise en cache
model_fr, tokenizer_fr, model_en, tokenizer_en = load_models()

# Fonction de résumé
def summarize(text):
    if not text.strip():
        return "Veuillez entrer un texte à résumer."

    try:
        lang = detect(text)
    except:
        return "Langue non détectée. Veuillez entrer un texte en français ou en anglais."

    with st.spinner('Génération du résumé en cours...'):
        if lang == 'fr':
            input_ids = tokenizer_fr.encode("summarize: " + text, return_tensors="pt", max_length=1024, truncation=True)
            output = model_fr.generate(input_ids, max_length=150, num_beams=4, early_stopping=True)
            summary = tokenizer_fr.decode(output[0], skip_special_tokens=True)
            return f"(Français détecté)\n\n{summary}"
        elif lang == 'en':
            input_ids = tokenizer_en.encode(text, return_tensors="pt", max_length=1024, truncation=True)
            output = model_en.generate(input_ids, max_length=150, num_beams=4, early_stopping=True)
            summary = tokenizer_en.decode(output[0], skip_special_tokens=True)
            return f"(Anglais détecté)\n\n{summary}"
        else:
            return "Langue non prise en charge (seulement français ou anglais)."

# Interface utilisateur Streamlit
col1, col2 = st.columns(2)

with col1:
    st.subheader("Texte à résumer")
    text_input = st.text_area("", height=400)

    if st.button("Générer le résumé"):
        with col2:
            st.subheader("Résumé")
            result = summarize(text_input)
            st.text_area("", value=result, height=400, disabled=True)

# Instructions pour exécuter sur Google Colab
st.sidebar.title("Instructions pour Google Colab")
st.sidebar.markdown("""
Pour exécuter cette application sur Google Colab:

1. Installez les dépendances nécessaires:
```python
!pip install transformers torch langdetect streamlit pyngrok
```

2. Sauvegardez ce code dans un fichier app.py:
```python
# Copiez le code de cette application
```

3. Exécutez l'application avec Ngrok:
```python
from pyngrok import ngrok
!streamlit run app.py &>/dev/null&
public_url = ngrok.connect(8501)
print(f"L'application est accessible à l'adresse: {public_url}")
```
""")